### ISSUE TITLE
proposal: add support to type string - format

### ISSUE THREAD

**Issue by Al-Pragliola** [omissis/go-jsonschema-fork#18]
in the README support to format is not listed, but it would be nice to validate also with [built-in formats](https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats)

example: 

```json
"email": {
    "type": "string",
    "format": "email"
}
```

**Comment by omissis** [comment]
moved to the original repo: https://github.com/omissis/go-jsonschema/issues/55
